name: Setup GitHub CLI

description: Install GitHub CLI (gh) if not already installed.

runs:
  using: "composite"
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        if ! type -p gh >/dev/null; then
          echo "Installing GitHub CLI (gh)..."
          sudo mkdir -p -m 755 /etc/apt/keyrings
          out=$(mktemp)
          wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg
          sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg < $out >/dev/null
          sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
          sudo apt update
          sudo apt install gh -y
        else
          echo "GitHub CLI (gh) is already installed."
        fi
